### PR TITLE
readme: add nix

### PR DESCRIPTION
**Pull request by ElysaSrc**
Add NixOS to the list of supported OS with details on how to use the derivation

### CODE REVIEW

**Review by isabelroses — APPROVED** [review]

**Comment by ElysaSrc** [comment]
(force pushed: fixed typo)

**Review by isabelroses — APPROVED** [review]

**Comment by ElysaSrc** [comment]
Thanks for merging quickly ❤️

**Comment by ecarlson94** [comment]
This doesn't work for me because of [this PR](https://github.com/catppuccin/sddm/pull/26). In fact, this only works for NixOS users that use Qt (which I don't). I had to remove this line to get the theme to work. This tells me that we should remove this line from here and manage Qt support within the install phase of the [catppuccin-sddm package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ca/catppuccin-sddm/package.nix) instead (it should be opt in with an option like `qt.enable`).

**Comment by ElysaSrc** [comment]
> This doesn't work for me because of [this PR](https://github.com/catppuccin/sddm/pull/26). In fact, this only works for NixOS users that use Qt (which I don't). I had to remove this line to get the theme to work. This tells me that we should remove this line from here and manage Qt support within the install phase of the [catppuccin-sddm package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ca/catppuccin-sddm/package.nix) instead (it should be opt in with an option like `qt.enable`).

I think we should not change it. NixOS is not the only OS supported, and if using NixOS unstable, currently you must change the sddm package to the Qt6 version (`pkgs.kdePackages.sddm`) because, by default, it starts the Qt5 version.

@isabelroses said on this issue: https://github.com/catppuccin/nix/pull/168#issuecomment-2111754109

> This seems like an issue you should take up with the upstream packager (nixpkgs). Since sddm is under the KDE banner so it makes sense for the catppuccin-sddm theme (and its maintainer, me) to ship it with the qt-platform set to 6 by default.

**Pull request merged**
